### ISSUE TITLE
Baseline model link broken

### ISSUE THREAD

**Issue by amit2319** [trushkin-ilya/face-anti-spoofer#29]
Can you share code for baseline models that are used for training the checkpoints, the sym-link in the repo seems to be broken.

**Comment by grib0ed0v** [comment]
@trushkin-ilya please take a look

**Comment by trushkin-ilya** [comment]
Hello @amit2319
I forgot to push changes for submodule package. Now it should work.

**Comment by amit2319** [comment]
@trushkin-ilya Thanks.

Now, I am not able to load the checkpoints with the feather-net model.

Sample Code:

> argparser.add_argument('--config-path', type=str, required=True)
> argparser.add_argument('--checkpoint', type=str, required=True)
> args = argparser.parse_args()
> config = yaml.load(open(args.config_path), Loader=yaml.FullLoader)
> device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
> model = getattr(models, config['model'])(num_classes=config['num_classes']).to(device)
> model.load_state_dict(torch.load(args.checkpoint, map_location=device))

Using model _FeatherNet_3ch_p1(19).pt_ in the checkpoints and _FeatherNetA_CE.yaml_ in config.

Getting the following issue in `model.load_state_dict(...)` :

> RuntimeError: Error(s) in loading state_dict for FeatherNet:
> 	Missing key(s) in state_dict: "features.2.fc.0.weight", "features.2.fc.0.bias", "features.2.fc.2.weight", "features.2.fc.2.bias", "features.5.fc.0.weight", "features.5.fc.0.bias", "features.5.fc.2.weight", "features.5.fc.2.bias", "features.12.fc.0.weight", "features.12.fc.0.bias", "features.12.fc.2.weight", "features.12.fc.2.bias", "features.13.conv.0.weight", "features.13.conv.1.weight", "features.13.conv.1.bias", "features.13.conv.1.running_mean", "features.13.conv.1.running_var", "features.13.conv.3.weight", "features.13.conv.4.weight", "features.13.conv.4.bias", "features.13.conv.4.running_mean", "features.13.conv.4.running_var", "features.13.conv.6.weight", "features.13.conv.7.weight", "features.13.conv.7.bias", "features.13.conv.7.running_mean", "features.13.conv.7.running_var", "features.14.conv.0.weight", "features.14.conv.1.weight", "features.14.conv.1.bias", "features.14.conv.1.running_mean", "features.14.conv.1.running_var", "features.14.conv.3.weight", "features.14.conv.4.weight", "features.14.conv.4.bias", "features.14.conv.4.running_mean", "features.14.conv.4.running_var", "features.14.conv.6.weight", "features.14.conv.7.weight", "features.14.conv.7.bias", "features.14.conv.7.running_mean", "features.14.conv.7.running_var", "features.15.conv.0.weight", "features.15.conv.1.weight", "features.15.conv.1.bias", "features.15.conv.1.running_mean", "features.15.conv.1.running_var", "features.15.conv.3.weight", "features.15.conv.4.weight", "features.15.conv.4.bias", "features.15.conv.4.running_mean", "features.15.conv.4.running_var", "features.15.conv.6.weight", "features.15.conv.7.weight", "features.15.conv.7.bias", "features.15.conv.7.running_mean", "features.15.conv.7.running_var", "features.16.fc.0.weight", "features.16.fc.0.bias", "features.16.fc.2.weight", "features.16.fc.2.bias", "fc.weight", "fc.bias". 
> 	Unexpected key(s) in state_dict: "classifier.weight", "classifier.bias", "features.2.conv.0.weight", "features.2.conv.1.weight", "features.2.conv.1.bias", "features.2.conv.1.running_mean", "features.2.conv.1.running_var", "features.2.conv.1.num_batches_tracked", "features.2.conv.3.weight", "features.2.conv.4.weight", "features.2.conv.4.bias", "features.2.conv.4.running_mean", "features.2.conv.4.running_var", "features.2.conv.4.num_batches_tracked", "features.2.conv.6.weight", "features.2.conv.7.weight", "features.2.conv.7.bias", "features.2.conv.7.running_mean", "features.2.conv.7.running_var", "features.2.conv.7.num_batches_tracked", "features.5.conv.0.weight", "features.5.conv.1.weight", "features.5.conv.1.bias", "features.5.conv.1.running_mean", "features.5.conv.1.running_var", "features.5.conv.1.num_batches_tracked", "features.5.conv.3.weight", "features.5.conv.4.weight", "features.5.conv.4.bias", "features.5.conv.4.running_mean", "features.5.conv.4.running_var", "features.5.conv.4.num_batches_tracked", "features.5.conv.6.weight", "features.5.conv.7.weight", "features.5.conv.7.bias", "features.5.conv.7.running_mean", "features.5.conv.7.running_var", "features.5.conv.7.num_batches_tracked", "features.12.conv.0.weight", "features.12.conv.1.weight", "features.12.conv.1.bias", "features.12.conv.1.running_mean", "features.12.conv.1.running_var", "features.12.conv.1.num_batches_tracked", "features.12.conv.3.weight", "features.12.conv.4.weight", "features.12.conv.4.bias", "features.12.conv.4.running_mean", "features.12.conv.4.running_var", "features.12.conv.4.num_batches_tracked", "features.12.conv.6.weight", "features.12.conv.7.weight", "features.12.conv.7.bias", "features.12.conv.7.running_mean", "features.12.conv.7.running_var", "features.12.conv.7.num_batches_tracked". 
> 	size mismatch for features.3.conv.0.weight: copying a param with shape torch.Size([192, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([96, 16, 1, 1]).
> 	size mismatch for features.3.conv.1.weight: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([96]).
> 	size mismatch for features.3.conv.1.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([96]).
> 	size mismatch for features.3.conv.1.running_mean: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([96]).
> 	size mismatch for features.3.conv.1.running_var: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([96]).
> 	size mismatch for features.3.conv.3.weight: copying a param with shape torch.Size([192, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([96, 1, 3, 3]).
> 	size mismatch for features.3.conv.4.weight: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([96]).
> 	size mismatch for features.3.conv.4.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([96]).
> 	size mismatch for features.3.conv.4.running_mean: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([96]).
> 	size mismatch for features.3.conv.4.running_var: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([96]).
> 	size mismatch for features.3.conv.6.weight: copying a param with shape torch.Size([32, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 96, 1, 1]).
> 	size mismatch for features.4.conv.6.weight: copying a param with shape torch.Size([48, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 192, 1, 1]).
> 	size mismatch for features.4.conv.7.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([32]).
> 	size mismatch for features.4.conv.7.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([32]).
> 	size mismatch for features.4.conv.7.running_mean: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([32]).
> 	size mismatch for features.4.conv.7.running_var: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([32]).
> 	size mismatch for features.6.conv.0.weight: copying a param with shape torch.Size([288, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([192, 32, 1, 1]).
> 	size mismatch for features.6.conv.1.weight: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
> 	size mismatch for features.6.conv.1.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
> 	size mismatch for features.6.conv.1.running_mean: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
> 	size mismatch for features.6.conv.1.running_var: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
> 	size mismatch for features.6.conv.3.weight: copying a param with shape torch.Size([288, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 1, 3, 3]).
> 	size mismatch for features.6.conv.4.weight: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
> 	size mismatch for features.6.conv.4.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
> 	size mismatch for features.6.conv.4.running_mean: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
> 	size mismatch for features.6.conv.4.running_var: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
> 	size mismatch for features.6.conv.6.weight: copying a param with shape torch.Size([48, 288, 1, 1]) from checkpoint, the shape in current model is torch.Size([48, 192, 1, 1]).
> 	size mismatch for features.10.conv.6.weight: copying a param with shape torch.Size([64, 288, 1, 1]) from checkpoint, the shape in current model is torch.Size([48, 288, 1, 1]).
> 	size mismatch for features.10.conv.7.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
> 	size mismatch for features.10.conv.7.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
> 	size mismatch for features.10.conv.7.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
> 	size mismatch for features.10.conv.7.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
> 	size mismatch for features.11.conv.0.weight: copying a param with shape torch.Size([384, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([288, 48, 1, 1]).
> 	size mismatch for features.11.conv.1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([288]).
> 	size mismatch for features.11.conv.1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([288]).
> 	size mismatch for features.11.conv.1.running_mean: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([288]).
> 	size mismatch for features.11.conv.1.running_var: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([288]).
> 	size mismatch for features.11.conv.3.weight: copying a param with shape torch.Size([384, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([288, 1, 3, 3]).
> 	size mismatch for features.11.conv.4.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([288]).
> 	size mismatch for features.11.conv.4.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([288]).
> 	size mismatch for features.11.conv.4.running_mean: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([288]).
> 	size mismatch for features.11.conv.4.running_var: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([288]).
> 	size mismatch for features.11.conv.6.weight: copying a param with shape torch.Size([64, 384, 1, 1]) from checkpoint, the shape in current model is torch.Size([48, 288, 1, 1]).
> 	size mismatch for features.11.conv.7.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
> 	size mismatch for features.11.conv.7.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
> 	size mismatch for features.11.conv.7.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
> 	size mismatch for features.11.conv.7.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).

Looks like a different model was used in training than available in _baseline_ here..

**Comment by amit2319** [comment]
@trushkin-ilya Any updates on this issue, am I doing something wrong  ?

**Comment by trushkin-ilya** [comment]
@amit2319 I'm sorry for late response. You are right: some provided links contain different models. We will provide links to correct models as soon as retraining process completes.
